### ISSUE TITLE
Python 2 style 'print' being used in Python 3?

### ISSUE THREAD

**Issue by mathemaphysics** [molmod/tamkin#14] opened 2018-09-29 04:45 UTC
Maybe there's a quick fix for this, but I noticed building and installing with pip that it allows building with Python >=3, but it uses Python 2 style print. I believe Python 3 has standardized print() to be like any function. So it just needs a quick run through with sed or awk to update it.

Correct me if I'm wrong.

**Comment by tovrstra** [comment] 2018-10-01 13:07
I did not port TAMkin to Python 3 yet. More things need to be fixed than just these print statements. I've done such transitions for other projects, so I know the drill. :)

**Comment by mathemaphysics** [comment] 2018-10-02 10:03
That makes sense then. Thanks! Installed in the wrong place.

**Comment by mathemaphysics** [comment] 2018-10-02 10:13
I'm just an obsessive personality. I often say more than I should. ;-)

Thanks again.

**Comment by tovrstra** [comment] 2018-10-02 10:19
I see. :) I'm going to re-open this because, technically, the issue is not solved yet. Keeping it open is a useful reminder and also informs others of the current situation. I'll close it as soon as the conversion to Py3 is done. This way you will also be the first to know.

**Comment by tovrstra** [comment] 2019-09-12 07:18
Done! Version 1.2.6 will be released today and it is compatible works with python 2.7, 3.6 and 3.7.

**Closed as completed by tovrstra** 2019-09-12 07:18 UTC
